### ISSUE TITLE
Replicating the simulation results

### ISSUE THREAD

**Issue by mr-asleep** [deepak3115/SIGNAL-PROCESSING-URLLC-NIT-ROURKELA#1]
Hey, I saw your query related to the complete code of the paper-"Deep Learning-Based Channel Estimation". I am working on the same project and came across this repo of yours. Were you able to complete the code by yourself and confirm the results mentioned in the paper?
Thanks in advance!!

**Comment by deepak3115** [comment]
with the available data set i was able to simulate and check my results with deep high performance of the paper. If the data sets for all SNR is available we can simulate the entire results.
